#!/bin/bash
#
# ~/.xinitrc
#
# Executed by startx

if [[ -d /etc/X11/xinit/xinitrc.d ]]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# From https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues
#
# see https://unix.stackexchange.com/a/295652/332452
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
# see https://wiki.archlinux.org/title/GNOME/Keyring#xinitrc
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK
# see https://github.com/NixOS/nixpkgs/issues/14966#issuecomment-520083836
mkdir -p "$HOME"/.local/share/keyrings

# Set background for X desktop (with 2 monitors optionally)
feh --bg-tile --no-fehbg ${HOME}/wallpapers/4-arch.jpg ${HOME}/wallpapers/4-arch.jpg

# Execute applications on startup
exec i3
